mysql:
  image: mysql:5.5
  ports:
    - 3306:3306
  volumes:
    - $PWD/src/main/resources/mysql:/docker-entrypoint-initdb.d:ro
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: example

#example:
#  image: com.github.jw3/example-akka-persistence:0.1
#  environment:
#    MYSQL_HOST: mysql
#    MYSQL_PASSWORD: root
